# Dot Dot Dot (...) | PyData New York 2018
> This talk makes no sense, but it's gonna be a lot of fun .

Imagine your boss gave you a problem to write a function to convert wavelength to frequency. The boss gives you a little code sample like this.

In [ ]:
# converts wavelength to frequency
def w2f(f):
    pass

print(f'w2f(1) -> {w2f(1)}')

w2f(1) -> None


Your boss can be a bit clever and write the above function in multiple ways as:

In [ ]:
def w2f(f):
    raise NotImplementedError
    
print(f'w2f(1) -> {w2f(1)}')

NotImplementedError: 

In [ ]:
# Or they could have a docstring telling you what to do
def w2f(f):
    ''' converts wavelength to optical frequency '''

Or they could do something like and you think that is something kind of weird.

In [ ]:
def w2f(f):
    ...

print(f'w2f(1) -> {w2f(1)}')

w2f(1) -> None


Now you google it and find that this was intended thing in python that allowed you to write incomplete code. You may have also seen these `Ellipsis` in some other places as below.

In [ ]:
...

Ellipsis

In [ ]:
Ellipsis

Ellipsis

In [ ]:
from numpy import arange
x = arange(25).reshape(5,5)

x[1, ...] # To get the first row

array([5, 6, 7, 8, 9])

In [ ]:
x = arange(27).reshape(3, 3, 3)
x

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
x[1, ...]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [ ]:
x[1, :]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [ ]:
x[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

Not you may think that ... is replacement for colon. But see below.

In [ ]:
x[:, 1]

array([[ 3,  4,  5],
       [12, 13, 14],
       [21, 22, 23]])

In [ ]:
x[..., 1]

array([[ 1,  4,  7],
       [10, 13, 16],
       [19, 22, 25]])

In [ ]:
greetings = dict(
    english = 'Hello!',
    
)

In [ ]:
greetings

{'english': 'Hello!'}

In [ ]:
a = ...

In [ ]:
... = 1

SyntaxError: cannot assign to Ellipsis (<ipython-input-20-891a8edba479>, line 1)

So you know that python is driven by a grammar and you can look up that file.

In [ ]:
from ast import parse

parse('x: ...')

In [ ]:
parse('x = ...')

In [ ]:
parse('True = False')

SyntaxError: cannot assign to True (<unknown>, line 1)

In [ ]:
parse('...: ...')

SyntaxError: illegal target for annotation (<unknown>, line 1)

In [ ]:
parse('... = ...')

SyntaxError: cannot assign to Ellipsis (<unknown>, line 1)

If you observe the two above examples you can see that we get two different errors when using : and = .

In [ ]:
a = '\N{heavy black heart}'
a

'❤'

In [ ]:
b = '\N{pile of poo}'
b

'💩'

This is valid python.

In [ ]:
def f(): ...

In [ ]:
def f(): {...:...}

In [ ]:
from __future__ import annotations
def  f() -> {...:...} : _._ : {...:...}